/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lendemark
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dodaj_ksiazke = new javax.swing.JButton();
        zamowienie = new javax.swing.JButton();
        Kom_Dodaj_auto = new javax.swing.JLabel();
        Kom_zamownie = new javax.swing.JLabel();
        wyloguj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dodaj_ksiazke.setText("Dodaj ksiazke");
        Dodaj_ksiazke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dodaj_ksiazkeActionPerformed(evt);
            }
        });

        zamowienie.setText("Zamówienie");
        zamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamowienieActionPerformed(evt);
            }
        });

        Kom_Dodaj_auto.setText("Dodawanie ksiazek do spisu w bazie ");

        Kom_zamownie.setText("Wybierz i zamów ksiażkę");

        wyloguj.setText("Wyloguj");
        wyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylogujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zamowienie)
                        .addGap(18, 18, 18)
                        .addComponent(Kom_zamownie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dodaj_ksiazke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Kom_Dodaj_auto))
                    .addComponent(wyloguj))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dodaj_ksiazke)
                    .addComponent(Kom_Dodaj_auto))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zamowienie)
                    .addComponent(Kom_zamownie))
                .addGap(18, 18, 18)
                .addComponent(wyloguj)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dodaj_ksiazkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dodaj_ksiazkeActionPerformed
        // TODO add your handling code here:
       
        new Dodaj_ksiazke().setVisible(true);
        menu.this.setVisible(false);
    }//GEN-LAST:event_Dodaj_ksiazkeActionPerformed

    private void zamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamowienieActionPerformed
        // TODO add your handling code here:
        new zamowienie().setVisible(true);
        menu.this.setVisible(false);
    }//GEN-LAST:event_zamowienieActionPerformed

    private void wylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylogujActionPerformed
        // TODO add your handling code here:
         new logMain().setVisible(true);
          menu.this.setVisible(false);
    }//GEN-LAST:event_wylogujActionPerformed





 



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dodaj_ksiazke;
    private javax.swing.JLabel Kom_Dodaj_auto;
    private javax.swing.JLabel Kom_zamownie;
    private javax.swing.JButton wyloguj;
    private javax.swing.JButton zamowienie;
    // End of variables declaration//GEN-END:variables
}
